sources:
  - name: Developer Dan's Hosts and Tracking List
    url: https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
    blocks_fb: false
  - name: Developer Dan's de-AMP List
    url: https://www.github.developerdan.com/hosts/lists/amp-hosts-extended.txt
    blocks_fb: false
  - name: Developer Dan's de-Facebook List
    url: https://www.github.developerdan.com/hosts/lists/facebook-extended.txt
    blocks_fb: true
  - name: Developer Dan's Hate and Junk List
    url: https://www.github.developerdan.com/hosts/lists/hate-and-junk-extended.txt
    blocks_fb: false
