files:
  - name: full
    whitelists: []
  - name: with-fb
    whitelists:
      - whatsapp
      - reddit
      - linkedin
      - twitter
  - name: adguard-compatible-without-fb
    description: >
      AdGuard for iOS seems to have a 500k domain limit. This excludes the domains in
      Steven Black's list to "work around" that.
    whitelists:
      - whatsapp
      - reddit
      - linkedin
      - twitter
  - name: adguard-compatible-with-fb
    description: >
      AdGuard for iOS seems to have a 500k domain limit. This excludes the domains in
      Steven Black's list to "work around" that.
    whitelists:
      - whatsapp
      - reddit
      - linkedin
      - twitter
  - name: without-fb
    whitelists:
      - reddit
      - linkedin
      - twitter
sources:
  - name: Developer Dan's Hosts and Tracking List
    url: https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
  - name: Developer Dan's de-AMP List
    url: https://www.github.developerdan.com/hosts/lists/amp-hosts-extended.txt
  - name: Developer Dan's Hate and Junk List
    url: https://www.github.developerdan.com/hosts/lists/hate-and-junk-extended.txt
  - name: Developer Dan's de-Facebook List
    url: https://www.github.developerdan.com/hosts/lists/facebook-extended.txt
    exclude_files:
      - without-fb
      - adguard-compatible-without-fb
  - name: Steven Black's Gambling and Fake News List
    url: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts
    exclude_files:
      - adguard-compatible-without-fb
      - adguard-compatible-with-fb
whitelists:
  - name: whatsapp
    patterns:
      - mmg-fna\.whatsapp\.net
      - mmg\.whatsapp\.net
      - whatsapp\.com
      - whatsapp\.net
      - whatsapp-.*fbcdn\.net
      - media-.*whatsapp\.net
      - media-.*\.cdn\.whatsapp.net
  - name: linkedin
    patterns:
      - linkedin\.com
      - media\.licdn\.com
      - static\.licdn\.com
      - www\.licdn\.com
      - www\.linkedin\.com
      - engineering\.linkedin\.com
  - name: twitter
    patterns:
      - t\.co
      - www\.t\.co
      - twimg\.com
      - twitter\.com
  - name: reddit
    patterns:
      - i\.redd\.it
      - i\.reddit\.com
      - www\.reddit\.com
      - preview\.redd\.it
      - preview\.redd\.it
      - oauth\.reddit\.com
      - reddit\.com
      - old\.reddit\.com
      - reddit\.map\.fastly\.net
      - v\.redd\.it
      - www\.redditstatic\.com
