files:
  - name: full
    description: >
      The whole enchilada. Includes all unique blocked domains from all of the lists
      below.
    whitelists: []
  - name: without-fb
    description: >
      All unique blocked domains from the lists below excluding those required to make
      Facebook work (which, unfortunately, also allows Facebook Ad Network tracking).
    whitelists:
      - reddit
      - linkedin
      - twitter
sources:
  - name: StevenBlack
    url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  - name: Developer Dan's de-Facebook List
    url: https://www.github.developerdan.com/hosts/lists/facebook-extended.txt
    exclude_files:
      - without-fb
{{ firebog }}
whitelists:
  - name: whatsapp
    patterns:
      - mmg-fna\.whatsapp\.net
      - mmg\.whatsapp\.net
      - whatsapp\.com
      - whatsapp\.net
      - whatsapp-.*fbcdn\.net
      - media-.*whatsapp\.net
      - media-.*\.cdn\.whatsapp.net
      - cdn.whatsapp.net
  - name: linkedin
    patterns:
      - linkedin\.com
      - media\.licdn\.com
      - static\.licdn\.com
      - www\.licdn\.com
      - www\.linkedin\.com
      - engineering\.linkedin\.com
  - name: twitter
    patterns:
      - t\.co
      - www\.t\.co
      - twimg\.com
      - twitter\.com
  - name: reddit
    patterns:
      - i\.redd\.it
      - i\.reddit\.com
      - www\.reddit\.com
      - preview\.redd\.it
      - preview\.redd\.it
      - oauth\.reddit\.com
      - reddit\.com
      - old\.reddit\.com
      - reddit\.map\.fastly\.net
      - v\.redd\.it
      - www\.redditstatic\.com
