---
on:
  push:
    branches:
      - main
    schedule:
      - cron: '* 5 * * *'
jobs:
  compile-hosts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate hosts files
        run: ./build_hosts.sh
      - name: Confirm hosts were created
        run: "stat ./hosts/{with,without}-fb.txt &>/dev/null || exit 1"
      - name: Store hosts as artifact
        uses: actions/upload-artifact@v3
        with:
          name: hosts
          path: hosts

  release-hosts:
    runs-on: ubuntu-latest
    needs: compile-hosts
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: hosts
      - name: Confirm hosts are present
        run: "stat *.txt &>/dev/null || exit 1"
      - name: Get current date
        id: date
        run: >
          echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S %Z')";
          echo "::set-output name=date-release::$(date +'%Y.%m.%d')";
      - name: Release latest version
        uses: softprops/action-gh-release@v1
        with:
          token: "${{secrets.GITHUB_TOKEN}}"
          files: '**.txt'
          tag_name: latest
          body: >
            These are Carlos's Hosts created on ${{ steps.date.outputs.date }}.
      - name: Release dated version
        uses: softprops/action-gh-release@v1
        with:
          token: "${{secrets.GITHUB_TOKEN}}"
          files: '**.txt'
          tag_name: "${{steps.date.outputs.date-release}}"
          body: >
            These are Carlos's Hosts created on ${{ steps.date.outputs.date }}.
            If you need the latest version, use the release tagged 'latest'.
